[package]
name = "wasm3"
version = "0.1.0"
authors = ["Lukas Tobias Wirth <lukastw97@gmail.com>"]
edition = "2018"
license = "MIT"

[features]
wasi = ["ffi/wasi"]
std = []
default = ["wasi", "std"]

[dependencies]
cty = "0.2"

[dependencies.ffi]
path = "wasm3-sys"
package = "wasm3-sys"

[workspace]
members = ["wasm3-sys"]