[package]
name = "wasm3"
version = "0.1.0"
authors = ["Lukas Tobias Wirth <lukastw97@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
wasm3-sys = {path = "wasm3-sys"}

[workspace]
members = ["wasm3-sys"]